[package]
name = "localbridge"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
colored = "2.0"
uuid = { version = "1", features = ["v4"] }
chrono = "0.4"
indicatif = "0.17"

